### ISSUE TITLE
Problem running the sample example given

### ISSUE THREAD

**Issue by noodlebreak** [ryanrhymes/panns#2]
EDIT 2:

My bad! I ran the example like this:
p = PannsIndex('euclidean')

This was from your github.io's page.

So obviously it got fucked up.

Please update your github.io page's example to properly initialize an object of PannsIndex.

Please close it now.

**Comment by noodlebreak** [comment]
Saw the your code now, and I think you should update the example to instantiate an object like this:

dim = 40  # or whatever
p = panns.PannsIndex(metric='euclidean', dimension=dim)

**Comment by ryanrhymes** [comment]
Thanks for the information. Also the valuable suggestion, very true. I will fix this issue asap. Actually, we will release a new version which will generate much smaller index file.
