### ISSUE TITLE
Issue with example on numpy 1.9.1

### ISSUE THREAD

**Issue by MaxwellRebo** [ryanrhymes/panns#3]
Here is the snippet:

```python
from panns import *

# create an index of Euclidean distance
p = PannsIndex('euclidean')

# generate a 1000 x 100 dataset
for i in xrange(1000):
   v = gaussian_vector(100)
   p.add_vector(v)

# build an index of 50 trees and save to a file
p.build(int(50))
#p.save('test.idx')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-b53e159ae9fd> in <module>()
    10 
    11 # build an index of 50 trees and save to a file
---> 12 p.build(int(50))
    13 #p.save('test.idx')

/Users/*****/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/panns/index.pyc in build(self, c)
   132         """
   133         num_prj = int(2 ** (numpy.log2(len(self.mtx) / self.K) + 1))
--> 134         self.prj = self.random_directions(num_prj)
   135         if self.parallel:
   136             self.mmap_core_data()

/Users/******/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/panns/index.pyc in random_directions(self, c)
   258         c: the number of principle components needed.
   259         """
--> 260         return [ gaussian_vector(self.dim, True, self.typ) for _ in xrange(c) ]
   261 
   262

/Users/******/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/panns/utils.pyc in gaussian_vector(size, normalize, dtype)
   112     normalize: the vector length is normalized to 1 if True.
   113     """
--> 114     v = numpy.random.normal(0,1,size)
   115     if normalize:
   116         v = v / linalg.norm(v)

/Users/****/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/random/mtrand.so in mtrand.RandomState.normal (numpy/random/mtrand/mtrand.c:12052)()

/Users/****/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/random/mtrand.so in mtrand.cont2_array_sc (numpy/random/mtrand/mtrand.c:2757)()

TypeError: an integer is required
```

I've tested this same example on numpy 1.8.0rc1, and it works perfectly. Perhaps this is a numpy bug in 1.9.1 where the casting is being done badly. The "self.dim" parameter somehow gets converted to something other than a C int.

If it seems that this is a numpy bug and not a panns bug, I can investigate that and do a PR on numpy instead, to resolve the issue.

Thanks!!

**Comment by ryanrhymes** [comment]
Thank you, Maxwell. It would be awesome if you can look into this numpy issue. I vaguely remember one of my colleagues had a similar issue, but later I think he managed to solve it somehow.

**Comment by MaxwellRebo** [comment]
Ok, I'll investigate further and comment back here once I know something. Thanks.

**Comment by rachelalbert** [comment]
I would like to use PANNS but I'm running into this same problem. It's been several months since this was posted - has it been fixed? I would prefer not to downgrade my numpy installation.

**Comment by ryanrhymes** [comment]
OK, I will look into this issue asap :)

**Comment by anfibil** [comment]
I'm also running into the same issue and was wondering if there had been any updates on how one might circumvent it. Thanks!

**Comment by MaxwellRebo** [comment]
I was never able to figure out what was going on with it. A second pass may be in order.

**Comment by ryanrhymes** [comment]
Hi chaps, I am terribly sorry for the delay. I got a bit overwhelmed by the research and conferences lately. Yes, I looked into this issue this afternoon and it turned out that it really has nothing to do with the version of numpy.

The actual problem is that the dimensionality must be explicitly defined in PannsIndex when you create it, or at least define it before you use it to build the tree. Namely, instead of writing like this -->
p = PannsIndex('euclidean')

you need to write like this -->
p = PannsIndex(dimension=100, metric='euclidean')

I tested your code my virtual machine with numpy 1.9 and it worked well. Let me know whether this solves your problem or not. If not, I will look deeper.

Sorry again for the delay, and thanks for reporting this. :+1:

**Comment by MaxwellRebo** [comment]
Ok. If the Pannsindex constructor requires dimension to be specified, then perhaps it should fail if it is not specified? It may be a matter of personal style, but if I'm going to need a parameter for something I'd rather be forced to specify it up front. Thoughts?

**Comment by ryanrhymes** [comment]
Yes, you are right, Maxwell. I think it is safer to explicitly specify  the dimensionality. It also eliminates the ambiguity. I will remove the default value in later. Thanks for the suggestion.
